module_1/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register')
]

module_1/applications/urls.py
from django.urls import path
from .views import ApplicationCreateView, ApplicationListView


urlpatterns = [
    path('create/', ApplicationCreateView.as_view(), name="create_application"),
    path('list/', ApplicationListView.as_view(), name="list_applications")
]

module_1/core/urls.py
from django.contrib import admin
from django.urls import path
from .views import home_view


urlpatterns = [
    path('', home_view, name='home')
]

module_1/module_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('applications/', include('applications.urls')),
]

module_1/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    first_name = None
    last_name = None
    
    full_name = models.CharField(max_length=255, verbose_name="ФИО")
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    

module_1/applications/models.py
from django.db import models
from accounts.models import User


SERVICE_CHOICES = [
    ("main", "Общий клининг"),
    ("general", "Генералньая уборка"),
    ("building", "Послестроительная уборка"),
    ("chemical", "химчистка ковров и мебели"),
]

PAYMENT_CHOICES = [
    ("cash", "Наличными"),
    ("card", "Картой"),
]

STATUS_CHOICES = [
    ("new", "Новая заявка"),
    ("completed", "Услуга оказана"),
    ("canceled", "Услуга отменена"),
]

class ApplicationModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, verbose_name="Адрес")
    contacts = models.CharField(max_length=100, verbose_name="Контактные данные")
    service_type = models.CharField(
        max_length = 8,
        choices = SERVICE_CHOICES,
        default = "main",
        verbose_name = "Вид услуги"
    )
    payment_type = models.CharField(
        max_length = 5,
        choices = PAYMENT_CHOICES,
        default = 'card',
        verbose_name = "Тип оплаты"
    )
    status = models.CharField(
        max_length = 10,
        choices = STATUS_CHOICES,
        default="new",
        verbose_name="Статус оказания услуги"
    )
    cancel_reason = models.TextField(blank=True, null=True, verbose_name="Причина отмены")
    
    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"
        
    def __str__(self):
        return f"Заявка №{self.id} от {self.author.full_name}"

module_1/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'full_name', 'phone_number', 'email', 'password1', 'password2']

module_1/applications/forms.py
from django import forms
from .models import ApplicationModel


class ApplicationModelForm(forms.ModelForm):
    
    class Meta:
        model = ApplicationModel
        fields = ("address", "contacts", "service_type", "payment_type")
        

module_1/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .forms import UserCreationForm
from django.urls import reverse_lazy


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("login")

module_1/applications/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .forms import ApplicationModelForm
from .models import ApplicationModel


class ApplicationCreateView(LoginRequiredMixin, CreateView):
    model = ApplicationModel
    form_class = ApplicationModelForm
    template_name = "ApplicationCreate.html"
    success_url = reverse_lazy("home")
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    

class ApplicationListView(LoginRequiredMixin, ListView):
    model = ApplicationModel
    template_name = "ApplicationList.html"
    context_object_name = "applications"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

module_1/accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Авторизация{% endblock %}

{% block content %}

{% if form.errors %}
<p>Пароль или логин не подоходят!</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>У вас нет доступа к этой странице!</p>
    {% else %}
    <p>Пожалуйста, авторизируйтесь для доступа к этой странице</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

module_1/accounts/templates/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}

{% if form.errors %}
{% for e in form.errors %}
    <a>{{ e }}</a><br/>
{% endfor%}
{% endif %}

<form method="post" action="{% url 'register' %}">
{% csrf_token %}
{{ form.as_p }}

<button class="btn btn-primary" type="submit">Регистрация</button>
</form>
{% endblock %}

module_1/applications/templates/ApplicationCreate.html
{% extends "base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %} 
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Создать</button>
</form>
{% endblock %}

module_1/applications/templates/ApplicationList.html
{% extends 'base.html' %}

{% block title %}Мои заявки{% endblock %}

{% block content %}
<a href="{% url 'create_application' %}" class="btn btn-primary">Новая заявка</a>
{% for a in applications %}
    <p>Адресс: {{ a.address }}</p>
    <p>Тип: {{ a.get_service_type_display }}</p>
    <p>Статус: {{ a.get_status_display }}</p>
    <br/>
{% empty %}
    <p>У вас пока нет заявок.</p>
{% endfor %}
{% endblock %}

module_1/core/templates/index.html
{% extends 'base.html'%}

{% block title %}Главная{% endblock %}

{% block content %}
<h1>Главная страница</h1>
{% endblock %}

module_1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Мой не сам | {% block title %}{% endblock %}</title>
    <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Главная</a>
        


        {% if user.is_authenticated %}
        <a href="{% url 'create_application' %}">Создать заявку</a>
        <a href="{% url 'list_applications' %}">Мои заявки</a>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Выйти</button>
        </form>
        {% else %}
        <a href="{% url 'login'%}">Войти</a>
        <a href="{% url 'register' %}">Регистрация</a>
        {% endif %}
        

    </nav>
    <main>
        {% block content %}
        
        {% endblock %}
    </main>
<script src="{% static 'js/bootstrap.min.js' %}"/>
</body>
</html>